It will allow us to view extra detail of a car
DiegoDevGroup/marketcheck-api-sdk-php pull request #2
Opened 2019-09-03 14:58 UTC by marcelooblan2016

- In viewing car details, this will allow us to access the extra details of a car so we can display it orderly.

2019-09-03 16:40 UTC, marcusmoore requested changes
Instead of making this `public`, can we keep it `private` and make a `getContainer` method instead? It would look similar to the `get*` (ie `getId`) methods already in this class.

2019-09-04 03:20 UTC, marcelooblan2016 commented
@marcusmoore , as for the update we have created a getter method for private $container ( getContainer  ).
Best regards,
marcelo

2019-09-04 04:49 UTC, marcusmoore approved these changes

2019-09-04 04:49 UTC, marcusmoore commented
@ericvanjohnson can you merge and tag a new release por favor?

2019-09-04 16:17 UTC, merged